config/routes.rb
TurboTrainer::Application.routes.draw do
  get 'home/index'
  devise_for :users

  root :to => 'home#index'

  resources :workouts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  include WorkoutStopwatch

  belongs_to :user
end

app/models/workout_stopwatch.rb
require 'date'
require 'time'

module WorkoutStopwatch

  def start!(clock=Time)
    self.started = clock.now
    self.save
  end

  def stop!(clock=Time)
    raise WorkoutNotStarted unless self.started

    self.finished = clock.now
    st = Time.parse(self.started.to_s)
    ft = Time.parse(self.finished.to_s)
    self.actual_duration = ft - st
    self.save
  end

  class WorkoutNotStarted < StandardError
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @workouts = current_user.workouts
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(params[:workout])
    @workout.user = current_user

    if @workout.start!
      current_user.workouts << @workout
      flash[:notice] = "Workout started"
      redirect_to workout_path(@workout)
    else
      render :new
    end
  end

  def update
    @workout = Workout.find(params[:id])
    @workout.stop!
    flash[:notice] = "Workout stopped"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Home

%p
  = link_to "New workout", new_workout_path, :class => "btn btn-primary btn-large"

%table{:class => "table table-bordered table-striped"}
  %thead
    %tr
      %th Started
      %th Finished
      %th Duration
      %th Actual Duration
    %tbody
    - @workouts.each do |workout|
      %tr
        %td= workout.started
        %td= workout.finished
        %td= workout.duration
        %td= workout.actual_duration

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Turbo Trainer
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', :debug => Rails.env.development?
    = csrf_meta_tag

  %body
    .navbar{:class => "navbar-fixed-top"}
      .navbar-inner
        .container
          = link_to "Turbo Trainer", home_index_path, :class => "brand"

          - if user_signed_in?
            %p{:class => "navbar-text pull-right"}
              = current_user.email
              = link_to "Sign out", destroy_user_session_path, :method => :delete

    .container
      = yield

    %footer
    %hr

app/views/workouts/new.html.haml
%h1 Start workout

= form_for @workout do |f|
  = f.label  :duration, 'Duration (minutes)'
  = f.select :duration, ['5', '10', '15', '20', '25', '30', '45', '60']

  = f.label      :media_url
  = f.text_field :media_url

  .form-actions
    = submit_tag 'Start', :class => "btn btn-primary"
    = link_to "Cancel", home_index_path, :class => "btn"

app/views/workouts/show.html.haml
%h1 Workout started

.row
  .span12
    #countdown_dashboard
      .dash.minutes_dash
        %span.dash_title minutes
        .digit 0
        .digit 0
      .dash.seconds_dash
        %span.dash_title seconds
        .digit 0
        .digit 0
%hr
.row
  .span12
    %video{:src => @workout.media_url, :style => "width:100%", :autoplay => true, :controls => true}

= form_for @workout do
  .form-actions
    = submit_tag 'Stop', :class => "btn btn-primary"
    = link_to "Cancel", home_index_path, :class => "btn"

:javascript
  jQuery(document).ready(function() {
    $('#countdown_dashboard').countDown({
        targetOffset: {
          'day':   0,
          'month': 0,
          'year':  0,
          'hour':  0,
          'min':   #{@workout.duration},
          'sec':   0
        }
    });
  });